/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Final;

/**
 *
 * @author SengLim
 */
public class Order_Option extends javax.swing.JFrame {

    /**
     * Creates new form Order_Option
     */
    public Order_Option() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1026, 520));
        setMinimumSize(new java.awt.Dimension(1026, 520));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        kButton3.setText("Korean Food");
        kButton3.setFont(new java.awt.Font("OCR A Extended", 2, 24)); // NOI18N
        kButton3.setkBorderRadius(250);
        kButton3.setkEndColor(new java.awt.Color(255, 0, 0));
        kButton3.setkForeGround(new java.awt.Color(0, 0, 51));
        kButton3.setkHoverForeGround(new java.awt.Color(204, 0, 0));
        kButton3.setkStartColor(new java.awt.Color(153, 153, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3);
        kButton3.setBounds(420, 240, 190, 190);

        kButton1.setText("Boba Tea");
        kButton1.setFont(new java.awt.Font("OCR A Extended", 2, 24)); // NOI18N
        kButton1.setkBorderRadius(250);
        kButton1.setkEndColor(new java.awt.Color(255, 0, 0));
        kButton1.setkForeGround(new java.awt.Color(0, 0, 51));
        kButton1.setkHoverForeGround(new java.awt.Color(204, 0, 0));
        kButton1.setkStartColor(new java.awt.Color(153, 153, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1);
        kButton1.setBounds(730, 240, 190, 190);

        kButton2.setText("Fast Food");
        kButton2.setFont(new java.awt.Font("OCR A Extended", 2, 24)); // NOI18N
        kButton2.setkBorderRadius(250);
        kButton2.setkEndColor(new java.awt.Color(255, 0, 0));
        kButton2.setkForeGround(new java.awt.Color(0, 0, 51));
        kButton2.setkHoverForeGround(new java.awt.Color(204, 0, 0));
        kButton2.setkStartColor(new java.awt.Color(153, 153, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2);
        kButton2.setBounds(100, 240, 190, 190);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Take a look at our menu ...!!!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 70, 610, 120);

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("WELCOME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 10, 200, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        Korean_Food.main(null);
        dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        Fast_Food.main(null);
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
       Boba_Tea.main(null);
       dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    // End of variables declaration//GEN-END:variables
}
