
package Final;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import javax.swing.JOptionPane;
public class Payment extends javax.swing.JFrame {
//    Fast_Food ff = new Fast_Food();
//    Korean_Food kk = new Korean_Food();
//    Boba_Tea bb = new Boba_Tea();
    Shop_Connection shop = new Shop_Connection();
    DecimalFormat df = new DecimalFormat("0.00");
    double total,discount,payment;
    double back;
    public Payment() {
        initComponents();
        shop.FetchData();
        tbtable.setModel(shop.getModel());
        txttotal.setText(String.valueOf(df.format(shop.getTotal()))+"$");
        txtpayment.setText(String.valueOf(df.format(shop.getTotal()))+"$");
    }
//    Collection data(){
//        ArrayList<ShopListtt> lr = new ArrayList<>();
//        for(ShopListtt temp : ShopListtt.list){
//            int code = temp.getCode();
//            String name = temp.getName();
//            int qty = temp.getQty();
//            double price = temp.getPrice();
//            double amount = temp.getAmount();
//            lr.add(new ShopListtt(code,name,qty,price,amount));
//        }
//        return lr;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtable = new rojeru_san.complementos.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        btcash = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        cbdiscount = new javax.swing.JComboBox<>();
        txtpayment = new javax.swing.JTextField();
        btback = new rojeru_san.complementos.RSButtonHover();
        txtcashreturn = new javax.swing.JTextField();
        txtdisprice = new javax.swing.JTextField();
        txtcashreceived = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1060, 612));
        setMinimumSize(new java.awt.Dimension(1060, 612));
        getContentPane().setLayout(null);

        tbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Qty", "Price", "Amount"
            }
        ));
        tbtable.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        tbtable.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        tbtable.setFont(new java.awt.Font("Romnea", 0, 14)); // NOI18N
        tbtable.setFuenteHead(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(tbtable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 90, 480, 370);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        btcash.setText("Cash");
        btcash.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btcash.setkHoverEndColor(new java.awt.Color(0, 0, 255));
        btcash.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcashActionPerformed(evt);
            }
        });
        jPanel1.add(btcash);
        btcash.setBounds(680, 480, 110, 45);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total : ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 90, 170, 50);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Discount :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 170, 50);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cash Return : ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 450, 170, 50);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 0, 170, 70);

        txttotal.setBackground(new java.awt.Color(0, 0, 0));
        txttotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txttotal);
        txttotal.setBounds(250, 90, 190, 50);

        cbdiscount.setBackground(new java.awt.Color(0, 0, 0));
        cbdiscount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbdiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "20%", "30%", "40%", "50%" }));
        cbdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdiscountActionPerformed(evt);
            }
        });
        jPanel1.add(cbdiscount);
        cbdiscount.setBounds(250, 160, 190, 50);

        txtpayment.setBackground(new java.awt.Color(0, 0, 0));
        txtpayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpayment.setForeground(new java.awt.Color(255, 255, 255));
        txtpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaymentActionPerformed(evt);
            }
        });
        jPanel1.add(txtpayment);
        txtpayment.setBounds(250, 300, 190, 50);

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        jPanel1.add(btback);
        btback.setBounds(20, 20, 100, 40);

        txtcashreturn.setBackground(new java.awt.Color(0, 0, 0));
        txtcashreturn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcashreturn.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtcashreturn);
        txtcashreturn.setBounds(250, 450, 190, 50);

        txtdisprice.setBackground(new java.awt.Color(0, 0, 0));
        txtdisprice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdisprice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdisprice);
        txtdisprice.setBounds(250, 230, 190, 50);

        txtcashreceived.setBackground(new java.awt.Color(0, 0, 0));
        txtcashreceived.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcashreceived.setForeground(new java.awt.Color(255, 255, 255));
        txtcashreceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcashreceivedKeyReleased(evt);
            }
        });
        jPanel1.add(txtcashreceived);
        txtcashreceived.setBounds(250, 370, 190, 50);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Disprice : ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 230, 170, 50);

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Payment : ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 300, 170, 50);

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cash Recieved : ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 370, 170, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     Collection data(){
        ArrayList<ShopListtt> lr = new ArrayList<>();
        for(ShopListtt temp : ShopListtt.list){
            int code = temp.getCode();
            String name = temp.getName();
            int qty = temp.getQty();
            double price = temp.getPrice();
            double amount = temp.getAmount();
            lr.add(new ShopListtt(code,name,qty,price,amount));
        }
        return lr;
    }
    
    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        Order_Option.main(null);
        dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void cbdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdiscountActionPerformed
        String dis = cbdiscount.getSelectedItem().toString();
        dis = dis.replace("%", "");
        double discount =Double.parseDouble(dis);
        payment = shop.getTotal()-(shop.getTotal()*discount)/100;
        txtdisprice.setText(String.valueOf((shop.getTotal() * discount) / 100)+"$");
        txtpayment.setText(String.valueOf(df.format(payment))+"$");
   //    double recieve = Double.parseDouble(txtcashreceived.getText());
   //    txtcashreturn.setText(String.valueOf(recieve - payment));
//          String t = txttotal.getText();
//          t=t.substring(0,t.length()-1);
//          double total = Double.parseDouble(t);
//          String dis = cbdiscount.getSelectedItem().toString();
//          dis=dis.substring(0,dis.length()-1);
//          int discount = Integer.parseInt(dis);
//          double disprice = total+discount/100;
//          double payment = total-disprice;
//          txtdisprice.setText(df.format(disprice));
//          txtpayment.setText(df.format(payment));
//    
    }//GEN-LAST:event_cbdiscountActionPerformed

    private void btcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcashActionPerformed
        try {
            //  double  total=shop.getTotal();
            String t = txttotal.getText();
            t=t.substring(0,t.length()-1);
            double total = Double.parseDouble(t);
            
            String disp = txtdisprice.getText();
            disp= disp.substring(0,disp.length()-1);
            double disprice = Double.parseDouble(disp);
            
            double recieve = Double.parseDouble(txtcashreceived.getText());
            
            String re = txtcashreturn.getText();
            re = re.substring(0,re.length()-1);
            double returned = Double.parseDouble(re);
            
         // double  total=shop.getTotal();
            String dis =cbdiscount.getSelectedItem().toString();
            dis=dis.substring(0,dis.length()-1);
            double discount=Double.parseDouble(dis);
            
            
            
            JasperReport jp = JasperCompileManager.compileReport("Report/Resturant.jrxml");
            HashMap pr = new HashMap();
            pr.put("total",shop.getTotal());
            pr.put("discount",discount/100);
            pr.put("disprice",disprice);
            pr.put("payment",payment);
            pr.put("recieve",recieve);
            pr.put("returned",returned);
            
           JRBeanCollectionDataSource jcd = new JRBeanCollectionDataSource(data());
           JasperPrint price = JasperFillManager.fillReport(jp, pr,jcd);
           JasperViewer.viewReport(price,false);
           
            //JasperPrintManager.printReport(price, true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btcashActionPerformed

    private void txtpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaymentActionPerformed

    private void txtcashreceivedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcashreceivedKeyReleased
        double recieve = Double.parseDouble(txtcashreceived.getText());
       txtcashreturn.setText(String.valueOf(recieve - payment));

    }//GEN-LAST:event_txtcashreceivedKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover btback;
    private com.k33ptoo.components.KButton btcash;
    private javax.swing.JComboBox<String> cbdiscount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tbtable;
    private javax.swing.JTextField txtcashreceived;
    private javax.swing.JTextField txtcashreturn;
    private javax.swing.JTextField txtdisprice;
    private javax.swing.JTextField txtpayment;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
