
package Final;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Sign_in extends javax.swing.JFrame {
    ImageIcon icon = new ImageIcon("D:\\Etec\\Java\\Pictures\\check-mark_5290058.png");
    ImageIcon icon1 = new ImageIcon("D:\\Etec\\Java\\Pictures\\cross_7699001.png");
    public Sign_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpw = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btlogin = new com.k33ptoo.components.KButton();
        btregister = new com.k33ptoo.components.KButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(840, 593));
        setMinimumSize(new java.awt.Dimension(840, 593));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 240, 70, 40);

        txtemail.setBackground(new java.awt.Color(255, 255, 255));
        txtemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(204, 0, 0));
        txtemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(50, 280, 250, 30);

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 20)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 320, 90, 40);

        txtpw.setBackground(new java.awt.Color(255, 255, 255));
        txtpw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpw.setForeground(new java.awt.Color(204, 0, 0));
        txtpw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtpw.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwActionPerformed(evt);
            }
        });
        jPanel1.add(txtpw);
        txtpw.setBounds(50, 360, 250, 30);

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("SIGN IN TO YOUR ACCOUNT");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 30, 550, 60);

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final/login.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 150, 160);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 60, 150, 160);

        btlogin.setText("LOGIN");
        btlogin.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btlogin.setkBorderRadius(50);
        btlogin.setkEndColor(new java.awt.Color(0, 0, 0));
        btlogin.setkHoverColor(new java.awt.Color(0, 255, 0));
        btlogin.setkHoverForeGround(new java.awt.Color(153, 0, 153));
        btlogin.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        jPanel1.add(btlogin);
        btlogin.setBounds(100, 440, 140, 45);

        btregister.setText("REGISTER");
        btregister.setToolTipText("");
        btregister.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btregister.setkBorderRadius(1000);
        btregister.setkEndColor(new java.awt.Color(153, 0, 153));
        btregister.setkHoverColor(new java.awt.Color(255, 255, 0));
        btregister.setkHoverForeGround(new java.awt.Color(153, 0, 153));
        btregister.setkHoverStartColor(new java.awt.Color(204, 204, 0));
        btregister.setkStartColor(new java.awt.Color(204, 0, 0));
        btregister.setName(""); // NOI18N
        btregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btregister);
        btregister.setBounds(490, 370, 240, 140);

        jPanel3.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final/click down.jpg"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 160, 200);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(520, 180, 160, 200);
        jPanel3.getAccessibleContext().setAccessibleName("");

        jLabel5.setFont(new java.awt.Font("Kh BL LazySmooth", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("New Here !?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(500, 140, 240, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwActionPerformed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        String email = txtemail.getText();
        String password = txtpw.getText().toString();
        boolean isemail = false;
        boolean ispassword = false;
        for(int i=0; i<Login_List.list.size(); i++){
            if(email.equals(Login_List.list.get(i).getEmail()))
            {
                isemail = true;
            }
            if(password.equals(Login_List.list.get(i).getPassword()))
            {
                ispassword = true;
            }
            //5. no data
            if(txtemail.equals(null) && txtpw.equals(null)){
                JOptionPane.showMessageDialog(null, "Pls Input Data..!!","Login",HEIGHT,icon1);
            }
            // 1. true all
            if(isemail==true && ispassword==true){
                JOptionPane.showMessageDialog(null, "Login Successful!", "Login", HEIGHT, icon);
                Order_Option.main(null);
                dispose();
            }
            //2. wrong email
            if(isemail==false && ispassword==true){
                JOptionPane.showMessageDialog(null, "Invalid Email..!!", "Login", HEIGHT, icon1);
            }
            //3. wrong pw
            if(isemail==true && ispassword==false){
                JOptionPane.showMessageDialog(null, "Invalid Password..!!", "Login", HEIGHT, icon1);
            }
            //4. wrong both
            if(isemail==false && ispassword==false){
                JOptionPane.showMessageDialog(null, "Invalid Data..!!", "Login", HEIGHT, icon1);
            }
            
        }
    }//GEN-LAST:event_btloginActionPerformed

    private void btregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregisterActionPerformed
       Sign_Up.main(null);
       dispose();
    }//GEN-LAST:event_btregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btlogin;
    private com.k33ptoo.components.KButton btregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtpw;
    // End of variables declaration//GEN-END:variables
}
